# Generated by Django 4.1.3 on 2023-01-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='Phone1',
            field=models.CharField(default='', max_length=12),
        ),
    ]
